#!/bin/sh

date_info=$(date +'%d.%m.%y | %V | %H:%M')
eth_status=$(nmcli | grep --max-count 1 'eno1')
last_update=$(awk 'END{sub(/\[/,""); sub(/\]/,""); print $1}' /var/log/pacman.log)

# get volume level
vol=$(amixer get Master | awk 'FNR==6 {gsub("\\[|\\]",""); print $5}')

# see if muted
if [[ $(amixer get Master | awk 'FNR==6 {print $6}') == "[off]" ]]; then
	vol="mute"
fi

# get time from last pacman -Syu
diff=$(datediff --format="%d d %H h" $last_update now)

echo -e "Last update: $diff ago \t vol: $vol \t $date_info"
