#!/bin/sh

date_info=$(date +'%d.%m.%Y %T')

# you cant just awk a specific line number because the number of lines change i think
bat_perc=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep "percentage" | awk '{print $2}')
bat_charge_status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep "state" | awk '{print $2}')

# get volume level
vol=$(amixer get Master | awk 'FNR==6 {gsub("\\[|\\]",""); print $5}')

# see if muted
if [[ $(amixer get Master | awk 'FNR==6 {print $6}') == "[off]" ]]; then
	vol="mute"
fi

# this is bad
tab=' '

echo vol: $vol "$tab" bat: $bat_perc "$tab" $date_info
