[colors.bright]
black = "0x383a42"
red = "0xd91254"
green = "0x0ebd0b"
yellow = "0x00ae8b"
blue = "0x0795d2"
magenta = "0xf906bf"
cyan = "0x0997b3"
white = "0xfafafa"

[colors.normal]
black = "0x383a42"
red = "0xd91254"
green = "0x0ebd0b"
yellow = "0x00ae8b"
blue = "0x0795d2"
magenta = "0xf906bf"
cyan = "0x0997b3"
white = "0xfafafa"

[colors.primary]
background = "0xfefefe"
foreground = "0x383a42"

dim_foreground = "0xaaaaaa"
